### ISSUE TITLE
Seem to stop files from being opened

### ISSUE THREAD

**Issue by scottwio** [Nopik/vim-nerdtree-direnter#1]
Hi I install the plugin and it seems to do the job hitting enter on a file no longer opens the files in a new tab. However it stops me from being able to open any files hitting return on a file does nothing, is this the intended behaviour?

.vimrc
      let NERDTreeMapOpenInTab='<Enter>'

There is Enter in the above but github is hiding it

**Comment by robertdxyz** [comment]
I am seeing the same issue

**Comment by Nopik** [comment]
Well, unfortunately Enter to open in new tab works for me, probably some other setting is in effect as well.

**Comment by joelruns** [comment]
Just open the vim script file and replace <Enter> with <CR> that's probably whats wrong.

**Comment by JakeSummers** [comment]
This doesn't work for me either... 

I tried the following: 
1. Install Nerdtree via pathogen
2. Install this via pathogen
3. Tried putting the following in my .vimrc: 

`let NERDTreeMapOpenInTab='<CR>'`

When I press enter on a directory, it opens the directory in a new tab.

**Comment by F1LT3R** [comment]
Seeing the same issue as well.

**Comment by chadfurman** [comment]
Check out the PR from @baumanno -- He just changed the <Enter> to <ENTER> in the plugin.  This fixed the problem for me.

**Comment by Gcaufy** [comment]
same to me, stop file form opening.
fixed after I added `let NERDTreeMapOpenInTab='<ENTER>'`
